---
name: Make

on:
  schedule:
    - cron:  '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: bash make.sh build

    - name: Attach Linux Build
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: flexpacket.ubuntu
        path: src/flexpacket

    - name: Build on Windows
      if: runner.os == 'Windows'
      shell: powershell
      run: pwsh -File make.ps1 build

    - name: Attach Windows Build
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: flexpacket.exe
        path: src/flexpacket.exe
